workflows:
  sample-workflow-id:
    environment: 
      # ...
    scripts: 
      # ...
    publishing: 
      email:
        recipients:
          - design.burakk@gmail.com
          - sercangoger@gmail.com
        notify:
          success: true
          failure: false
